import jsPDF from "jspdf";
import type { Scan } from "@/hooks/useScans";

const BRAND = "VERIFACT";
const TAGLINE = "Forensic Analysis Report";

function setHeader(doc: jsPDF, pageW: number) {
  // Gradient-ish header band
  doc.setFillColor(33, 70, 200);
  doc.rect(0, 0, pageW, 28, "F");
  doc.setFillColor(140, 90, 220);
  doc.rect(0, 24, pageW, 4, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(BRAND, 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(TAGLINE, 14, 21);

  doc.setFontSize(8);
  doc.text(new Date().toLocaleString(), pageW - 14, 14, { align: "right" });
}

function setFooter(doc: jsPDF, pageW: number, pageH: number) {
  doc.setDrawColor(220);
  doc.line(14, pageH - 18, pageW - 14, pageH - 18);
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by Verifact · AI-assisted forensic analysis", 14, pageH - 12);
  doc.text("Confidential", pageW - 14, pageH - 12, { align: "right" });
}

function sectionTitle(doc: jsPDF, y: number, title: string) {
  doc.setFillColor(245, 247, 252);
  doc.rect(14, y - 5, doc.internal.pageSize.getWidth() - 28, 8, "F");
  doc.setTextColor(33, 70, 200);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(title.toUpperCase(), 17, y);
  return y + 8;
}

function kv(doc: jsPDF, y: number, k: string, v: string, pageW: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(60);
  doc.text(k, 17, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30);
  const lines = doc.splitTextToSize(v || "—", pageW - 80);
  doc.text(lines, 70, y);
  return y + Math.max(6, lines.length * 5);
}

function verdictColor(category?: string): [number, number, number] {
  if (category === "authentic") return [34, 168, 90];
  if (category === "suspicious") return [240, 160, 30];
  if (category === "manipulated" || category === "fake") return [220, 50, 60];
  return [120, 120, 120];
}

function ensureSpace(doc: jsPDF, y: number, needed: number, pageW: number, pageH: number) {
  if (y + needed > pageH - 22) {
    setFooter(doc, pageW, pageH);
    doc.addPage();
    setHeader(doc, pageW);
    return 38;
  }
  return y;
}

export function generateForensicReport(scan: Scan) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  setHeader(doc, pageW);

  // Title block
  let y = 42;
  doc.setTextColor(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(`${scan.scan_type.toUpperCase()} ANALYSIS`, 14, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(scan.input_label || `${scan.scan_type} scan`, 14, y);
  y += 10;

  // Verdict pill
  const details = (scan.details ?? {}) as Record<string, any>;
  const cat = details.category;
  const [r, g, b] = verdictColor(cat);
  doc.setFillColor(r, g, b);
  doc.roundedRect(14, y, 70, 14, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text((scan.verdict || "Unknown").toUpperCase(), 49, y + 9, { align: "center" });

  // Confidence ring (textual)
  doc.setTextColor(20);
  doc.setFontSize(28);
  doc.text(`${scan.confidence ?? 0}%`, pageW - 30, y + 11, { align: "right" });
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Confidence", pageW - 30, y + 16, { align: "right" });

  y += 24;

  // Metadata section
  y = sectionTitle(doc, y, "Scan metadata");
  y = kv(doc, y, "Scan ID", scan.id, pageW);
  y = kv(doc, y, "Type", scan.scan_type, pageW);
  y = kv(doc, y, "Source", scan.source_type || "—", pageW);
  y = kv(doc, y, "Created", new Date(scan.created_at).toLocaleString(), pageW);
  y += 4;

  // Summary / analysis
  if (details.analysis || details.aiExplanation) {
    y = ensureSpace(doc, y, 30, pageW, pageH);
    y = sectionTitle(doc, y, "Forensic summary");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(40);
    const text = String(details.aiExplanation || details.analysis);
    const lines = doc.splitTextToSize(text, pageW - 28);
    lines.forEach((ln: string) => {
      y = ensureSpace(doc, y, 6, pageW, pageH);
      doc.text(ln, 17, y);
      y += 5;
    });
    y += 4;
  }

  // Detection scores
  const scores: Record<string, number> | undefined =
    details.detectionScores || details.scores;
  if (scores && Object.keys(scores).length) {
    y = ensureSpace(doc, y, 12 + Object.keys(scores).length * 9, pageW, pageH);
    y = sectionTitle(doc, y, "Detection scores");
    Object.entries(scores).forEach(([k, v]) => {
      const val = typeof v === "number" ? Math.round(v) : 0;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(60);
      doc.text(k.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase()), 17, y);
      // bar
      const barX = 80, barW = pageW - 110;
      doc.setFillColor(235, 238, 245);
      doc.roundedRect(barX, y - 3.5, barW, 4, 1, 1, "F");
      const fillW = (Math.max(0, Math.min(100, val)) / 100) * barW;
      const [br, bg, bb] = val > 70 ? [220, 50, 60] : val > 40 ? [240, 160, 30] : [34, 168, 90];
      doc.setFillColor(br, bg, bb);
      doc.roundedRect(barX, y - 3.5, fillW, 4, 1, 1, "F");
      doc.setTextColor(40);
      doc.text(`${val}%`, pageW - 17, y, { align: "right" });
      y += 7;
    });
    y += 4;
  }

  // Effects / propaganda techniques / risk flags
  const effects: any[] | undefined =
    (scan.effects as any[]) || details.effects || details.propaganda || details.riskFlags;
  if (Array.isArray(effects) && effects.length) {
    y = ensureSpace(doc, y, 14 + effects.length * 7, pageW, pageH);
    y = sectionTitle(doc, y, "Detected indicators");
    effects.forEach((e: any) => {
      const name = e?.name || e?.technique || e?.label || String(e);
      const sev = e?.severity || e?.level || "";
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(40);
      doc.text(`• ${name}${sev ? `  (${sev})` : ""}`, 17, y);
      y += 6;
      y = ensureSpace(doc, y, 6, pageW, pageH);
    });
    y += 4;
  }

  // Disclaimer
  y = ensureSpace(doc, y, 24, pageW, pageH);
  y = sectionTitle(doc, y, "Disclaimer");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(110);
  const disc = doc.splitTextToSize(
    "This report is generated by AI-assisted forensic models and should be treated as supporting evidence, not as a definitive judgement. Always verify critical claims through independent sources and human expertise.",
    pageW - 28,
  );
  doc.text(disc, 17, y);

  setFooter(doc, pageW, pageH);

  const fname = `verifact-${scan.scan_type}-${scan.id.slice(0, 8)}.pdf`;
  doc.save(fname);
}