project_id = "wobllgntstatmwgtgnpk"

[functions.verify-text]
verify_jwt = false

[functions.verify-image]
verify_jwt = false

[functions.verify-video]
verify_jwt = false

[functions.verify-url]
verify_jwt = false

[functions.truth-chat]
verify_jwt = false
