// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-scans.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-scans.ts
var list_scans_default = defineTool({
  name: "list_scans",
  title: "List verification scans",
  description: "List the signed-in user's recent VeriFact verification scans (text, image, video, audio, url, document) with verdict and confidence.",
  inputSchema: {
    scan_type: z.enum(["text", "image", "video", "url", "audio", "document"]).optional().describe("Optional filter by scan type."),
    limit: z.number().int().optional().describe("Max scans to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ scan_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("scans").select("id, scan_type, input_label, verdict, confidence, source_type, created_at").order("created_at", { ascending: false }).limit(take);
    if (scan_type) query = query.eq("scan_type", scan_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { scans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-scan.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_scan_default = defineTool2({
  name: "get_scan",
  title: "Get scan details",
  description: "Fetch the full forensic result of one of the signed-in user's VeriFact scans by id, including scores, indicators and explanation.",
  inputSchema: { id: z2.string().describe("The scan id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("scans").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No scan found with id ${id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scan: data }
    };
  }
});

// src/lib/mcp/tools/verify-text.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var verify_text_default = defineTool3({
  name: "verify_text",
  title: "Verify a news claim",
  description: "Run VeriFact's news verification on a claim, headline or article. Cross-references live news, fact-checkers and social platforms and returns a verdict with probabilities and evidence.",
  inputSchema: { text: z3.string().describe("The claim, headline or article text to verify.") },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ text }) => {
    const claim = text.trim();
    if (!claim) throw new ToolError("text must not be empty");
    const res = await fetch(`${supabaseProjectUrl()}/functions/v1/verify-text`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: supabasePublishableKey(),
        Authorization: `Bearer ${supabasePublishableKey()}`
      },
      body: JSON.stringify({ text: claim })
    });
    const body = await res.text();
    if (!res.ok) throw new ToolError(`Verification failed (${res.status}): ${body.slice(0, 400)}`);
    let result;
    try {
      result = JSON.parse(body);
    } catch {
      throw new ToolError("Verification returned an unreadable response");
    }
    const summary = [
      `Verdict: ${result.verifiedVerdict ?? result.verdict ?? "unknown"}`,
      `Confidence: ${result.confidence ?? "n/a"}%`,
      result.probabilities ? `Probabilities \u2014 real ${result.probabilities.real}% / misleading ${result.probabilities.misleading}% / fake ${result.probabilities.fake}%` : "",
      result.aiExplanation || result.analysis || ""
    ].filter(Boolean).join("\n");
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { result }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wobllgntstatmwgtgnpk";
var mcp_default = defineMcp({
  name: "verifact",
  title: "veriFact",
  version: "0.1.0",
  instructions: "Tools for VeriFact, a forensic AI verification platform. Use `verify_text` to fact-check a news claim, headline or article against live news, fact-checkers and social platforms. Use `list_scans` and `get_scan` to read the signed-in user's past verification scans across text, image, video, audio, URL and document analysis.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [verify_text_default, list_scans_default, get_scan_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
